config/routes.rb
BookTracker::Application.routes.draw do
  resources :books
  get "marketing_pages/home"
  root to: "books#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: true
  has_attached_file :pdf_book
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @colors = %w( pink sand light-sand light-blue ).cycle
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to root_path
  end

  def show
    @book = Book.find(params[:id])
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :description, :uploaded_pdf)
    end
end

app/controllers/marketing_pages_controller.rb
class MarketingPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/marketing_pages_helper.rb
module MarketingPagesHelper
end

app/views/books/_book_submit_form.html.erb
<div id="dialog-form" title="Create new book">
  <%= form_for(:book, html: {multipart: true}) do |f| %>
  <% if @book.errors.any? %>
  <%= "errors." %>
  <% end %>
  <p>
    <%= f.label :title %></br>
    <%= f.text_field :title %>
  <p>
    <%= f.label :author %></br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :description %></br>
    <%= f.text_area :description, cols: '30', rows: '10' %>
  </p>
  <p>
    <%= f.label :pdf_book %>
    <%= f.file_field :pdf_book %>
  </p>
  <p>
    <%= f.button %>
  </p>
  <% end %>
</div>

app/views/books/index.html.erb
<div class="bookshelf">
  <header>
    Your Bookshelf
  </header>

  <div class="books">
  <section>
    <% @books.each do |book| %>
      <article class="h <%= @colors.next %>">
        <%= link_to book.title, book_path(book) %></br>
        <%= book.author %>
      </article>
    <% end %>
    <article class="h" id="new-book">
      <svg width="82" height="82">
        <circle cx="41" cy="41" r="40" fill="orange" />
      </svg>
    </article>
  </section>
  <%= render 'books/book_submit_form' %>
</div>
</div>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<canvas id="the-canvas" style="border:1px solid black"></canvas>
  <script type="text/javascript">
    var url = 'http://cdn.mozilla.net/pdfjs/<%= "helloworld" %>.pdf';
    PDFJS.disableWorker = true;
    PDFJS.getDocument(url).then(function getPdfHelloWorld(pdf) {
      pdf.getPage(1).then(function getPageHelloWorld(page) {
        var scale = 1;
        var viewport = page.getViewport(scale);

        var canvas = document.getElementById('the-canvas');
        var context = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;

        page.render({canvasContext: context, viewport: viewport});
      });
    });
  </script>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <p>Application by Sung Kim. <a href='http://www.github.com/jstkim7'>Github</a><p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
    <div class="logo"><%= link_to "Book Tracker", root_path %></div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/marketing_pages/home.html.erb
<h1>MarketingPages#home</h1>
<p>Find me in app/views/marketing_pages/home.html.erb</p>